version: "3.8"
services: 
    backend:
        build: ./backend
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        ports:
          - "8000:8000"
        volumes:
          - ./backend/conf/:/backend/
    frontend:
        build: ./frontend
        container_name: react
        command: npm start
        ports:
          - "3000:3000"
        volumes:
          - ./frontend/capsulator/:/frontend/
    redis:
        image: redis
        ports:
          - "6379:6379"
    worker:
        restart: always
        build: ./backend
        command: celery -A conf worker -l info
        depends_on: 
          - redis
        environment: 
          - CELERY_BROKER=redis://redis:6379/0
          - CELERY_BACKEND=redis://redis:6379/0
        volumes:
          - ./backend/conf/:/backend/

