# Generated by Django 3.1.7 on 2021-05-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='public',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
