# Generated by Django 3.1.7 on 2021-05-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsulator', '0003_auto_20210528_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'Created'), (1, 'Locked'), (2, 'Opened')], default=0, null=True),
        ),
    ]
