# Generated by Django 3.1.7 on 2021-05-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsulator', '0005_auto_20210529_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capsule',
            old_name='isPublic',
            new_name='is_public',
        ),
    ]
