# Generated by Django 3.1.7 on 2021-06-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsulator', '0009_auto_20210531_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='unlocking_date',
            field=models.DateTimeField(default='2021-06-01 09:18:23.991062'),
            preserve_default=False,
        ),
    ]
