# Generated by Django 3.1.7 on 2021-06-02 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capsulator', '0010_auto_20210601_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(default='http://127.0.0.1:3000/logo.png', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capsule',
            name='unlocking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capsulator.member'),
        ),
    ]
