# Generated by Django 3.1.7 on 2021-06-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsulator', '0011_auto_20210602_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(default='sjkhdkfjhsjkdfh', max_length=100),
            preserve_default=False,
        ),
    ]
