# Generated by Django 3.1.7 on 2021-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsulator', '0012_user_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sub',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
